### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by mvbrooks** [techequitycollaborative/tenantprotections2#33]
Get final and correct Spanish translations on all copy

**Comment by Carababusha** [comment]
Hi @mvbrooks!

I've found the existing Spanish common.json translation in the ES locale folder. It's good, but it could do with a revision to standardize use of pronouns and a couple of other things. Would you like me to edit it for you?

**Comment by mvbrooks** [comment]
@Carababusha Hi, thanks so much for your interest in the project, and that would be fantastic and much appreciated. Feel free to do a pull request with any edits.

**Comment by mvbrooks** [comment]
@Carababusha We should have all of the copy finalized by the middle of this week, and we are planning to release next week. Would you be willing to take one more pass through the changes sometime late this week/weekend? Thank you!

**Comment by Carababusha** [comment]
@mvbrooks Of course! Just let me know what is ready for review when and I'll be happy to review it for you in time for the planned release date ☺️

**Comment by mvbrooks** [comment]
@Carababusha Thank you! We have a big batch of changes in, so if you're able to take a look this weekend that would be amazing.

**Comment by Carababusha** [comment]
Done @mvbrooks! Just created pull request #81 to contribute a review of he Spanish copy. 

Hope it's useful!

**Comment by mvbrooks** [comment]
@Carababusha Thank you!

I would love to have you join our civic tech team and also credit you on the site by name. If that's something you're interested in, you can fill out this form to connect with me directly rather than posting contact info on github: https://techequitycollaborative.org/civic-tech-projects/#form

**Comment by Carababusha** [comment]
@mvbrooks Thank you for that! I've signed up on the form, so hopefully I can help again whenever you need it 😊
