### ISSUE TITLE
Can change zipcode and select city on second page

### ISSUE THREAD

**Issue by arushibandi** [techequitycollaborative/tenantprotections2#84]
Not necessarily a bug, but if you select `90002` for example as the zip, on the next page it asks you to choose the city, but you can also change the zip code. so i can get into a state where i have 94114 selected as the zip code and Los Angeles as the city, and it uses 94114 to continue the quiz

**Comment by mvbrooks** [comment]
Related issue, you can directly navigate to mismatching zip/city via url.

We should check that things match before displaying a page. It might make sense to lock the zip field for the city select as well, as long as there's an intuitive way for the user to go back to edit the zip.

**Comment by iconshocking** [comment]
You shouldn't be able navigate to a mismatching city and zip. I previously put in a check for it in `tryEnrichLocation()`, so you should get a redirect to the root of whatever flow you were in if the combo isn't valid.

**Comment by mvbrooks** [comment]
Thanks @iconshocking for https://github.com/techequitycollaborative/tenantprotections2/pull/91 which fixed the first issue!

I'm still seeing the ability to directly navigate to a mismatched zip/city, can reproduce with /eligibility/zip/94101/city/Oakland

**Comment by iconshocking** [comment]
Got it. It's only an issue for zip codes with only one city option. Fixed in the linked PR.
